### PR TITLE
cargo: update dependencies

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

### CODE REVIEW

**Comment by vbatts** [comment]
should rebase once #5 is merged.

**Review by invidian — APPROVED** [review]

**Comment by pothos** [comment]
See https://github.com/kinvolk/afterburn/pull/12#discussion_r589787816, we first need to test the coreos-overlay ebuild file and also bump the commit once changes are merged here.

**Review by dongsupark — APPROVED** [review]

**Comment by vbatts** [comment]
rebased to use the rust action

**Comment by pothos** [comment]
Thanks, in https://github.com/flatcar/update-ssh-keys/pull/7 I've also ran `cargo update` (the same was also done on `master` by CoreOS folks since we branched) and tested building and running.

**Pull request closed without merging**
